CREATE TABLE t_user(
`USER_ID_` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '用户id',
`USER_NAME_` VARCHAR(255) NOT NULL COMMENT '用户姓名',
`PASSWORD_` VARCHAR(255) NOT NULL COMMENT '用户密码',
`PHONE_` VARCHAR(255)  DEFAULT NULL COMMENT '用户手机号'
)ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE `module` (
  `M_ID_` int(11) NOT NULL AUTO_INCREMENT COMMENT '权限ID',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '权限名称',
  PRIMARY KEY (`M_ID_`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='权限表';

DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
  `ID_` int(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '角色名称',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='角色表';

DROP TABLE IF EXISTS `user_role`;
CREATE TABLE `user_role` (
  `USER_ID_` int(11) DEFAULT NULL COMMENT '用户ID',
  `ROLE_ID_` int(11) DEFAULT NULL COMMENT '角色ID',
  KEY `u_fk` (`USER_ID_`),
  KEY `r_fk` (`ROLE_ID_`),
  CONSTRAINT `r_fk` FOREIGN KEY (`ROLE_ID_`) REFERENCES `role` (`ID_`),
  CONSTRAINT `u_fk` FOREIGN KEY (`USER_ID_`) REFERENCES `t_user` (`USER_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户角色关联表';

DROP TABLE IF EXISTS `module_role`;
CREATE TABLE `module_role` (
  `ID_` int(11) DEFAULT NULL COMMENT '权限ID',
  `M_ID_` int(11) DEFAULT NULL COMMENT '角色ID',
  KEY `ID_` (`ID_`),
  KEY `M_ID_` (`M_ID_`),
  CONSTRAINT `M_ID_` FOREIGN KEY (`M_ID_`) REFERENCES `module` (`M_ID_`),
  CONSTRAINT `ID_` FOREIGN KEY (`ID_`) REFERENCES `role` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色权限关联表';
